# install.yml
---

  - name: install HAProxy
    package:
     name: haproxy
  - name: allow service to start
    lineinfile:
     dest: /etc/default/haproxy
     regexp: ENABLED=.*
     line: ENABLED=1
  - name: Install config file
    template: 
      src: roles/haproxy/templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify:
    - reload HAProxy service
  - name: Start / enable HAProxy
    service: 
      name: haproxy
      enabled: true
      state: started
  - name: include tests
    include_tasks: tests.yml
    tags: tests
