# install.yml
---

- hosts: app-servers
  gather_facts: true
  become: truE
  tasks:
  - name: install tomcat
    package: 
     name: tomcat8
  - name: start / enable tomcat
    service: 
     name: tomcat8
     enabled: true
     state: started
  - name: wait for Tomcat to be up on port 8080
    wait_for:
     port: 8080
  - name: ensure home page returns 200
    uri:
      url: http://127.0.0.1:8080/
      timeout: 240
       

- hosts: load-balancers
  gather_facts: true
  become: true
  tasks:
  - name: install HAProxy
    package:
     name: haproxy
  - name: allow service to start
    lineinfile:
     dest: /etc/default/haproxy
     regexp: ENABLED=.*
     line: ENABLED=1
  - name: Install config file
    template: 
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
  - name: Start / enable HAProxy
    service: 
      name: haproxy
      enabled: true
      state: started
  - name: wait for HAProxy to be up on port 8080
    wait_for:
      port: 8080
  - name: wait for HAProxy to be up on port 80
    wait_for:
      port: 80
  - name: ensure stat page returns 200
    uri:
      url: http://127.0.0.1:8080/
