# install.yml
---

- hosts: app-servers
  gather_facts: true
  become: true
  roles:
  - role: tomcat
    tags: tomcat 
       

- hosts: load-balancers
  gather_facts: true
  become: true
  roles:
  - role: haproxy
    tags: haproxy
