# roles/tomcat-app/tasks/check_deploy_needed.yml

---

 - name: Get currently running application version
   uri: 
     url: http://localhost:8080/{{ tomcat_app_name }}/version
     return_content: yes
   failed_when: false
   register: tomcat_app_predeploy_version

 - name: Compute whether deploymentis needed
   set_fact: 
     tomcat_app_needs_deploy: tomcat_app_predeploy_version.status != 200 or (tomcat_app_predeploy_version.json.version != '{{ tomcat_app_version }}')
     
